version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # RabbitMQ (nếu bạn dùng message-broker kiểu AMQP)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - customer-service
    networks:
      - app-network

  # Order Service
  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/orderdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  # Customer Service
  customer-service:
    build: ./services/customer-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/customerdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
      
volumes:
  mongo_data:

networks:
  app-network: